# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true

# Minecraft
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.1
loader_version=0.16.14

# Fabric API
fabric_version=0.140.0+1.21.11

# Architectury
architectury_version=19.0.1

# Mod
mod_version=0.1
mod_id=tradeschool
mod_name=Trade School
mod_group=cx.gid.minecraft
archives_base_name=tradeschool
